# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 195de43c93ee5226b27c517032e16bf284d8a30cee44bf992ab7a6b223a786ad92e98b42866c8f16f0dde252274d462c27ec1bf6ea74cc3f95c26d17100c1111

test:
  secret_key_base: 1af6ab66a384607087a8355982a213bb5014f96a87e473c21df50e2dbad0ead9b687c66e524f73b1a87be17d4369b3935f9731d574757f87bc9adf11e2d13198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
