# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09dc62743ec50fb90537462c0fb1eb5f9718619c7003aef3911aece2f10b2bb16a6468bed471d9874ab9cbc8f258987a39b219ff8242e51e41b2603b09ccfeee

test:
  secret_key_base: 6636fdf36b8b6ddf15e1bacd5f55915f7e9893b8c3900261c51f77ebea7c3af81cc0e7a3eb84f1c09950d64ee3f1b217321edd9fb025808515b95cdad30173ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
