source 'https://rubygems.org'

gem 'slim'
gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'carrierwave'
gem 'bootstrap-sass'

group :development, :test do
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'byebug'
  gem 'spring'
  gem 'pry'
end

group :test do
  gem 'capybara'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'guard-rspec', require: false
end
